### ISSUE TITLE
update & submit to helm/charts?

### ISSUE THREAD

**Issue by billimek** [imubit/graylog-helm-chart#2]
Hi @imubit, do you have any desire or expectation to update this (e.g. implement #1 ) and submit as a formal chart to the [helm/charts](https://github.com/helm/charts) repo?

I'd like to try to do this, but will hold-off if you already have plans.

**Comment by cloud-rocket** [comment]
Sorry, no plans for now.

**Comment by billimek** [comment]
Ok thanks!
